/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.teste;

/**
 *
 * @author kelvin.melim
 */
public class visual extends javax.swing.JFrame {

    /**
     * Creates new form visual
     */
    public visual() {
        initComponents();
    }
    public void teste(){
        fTextField.setText("1. O gerenciamento do escopo do projeto inclui os processos \n necessários para assegurar que o projeto"
                            +  "\n inclua todo o trabalho, e apenas o necessário, para que termine com sucesso. \n" +
                            "Qual das opções abaixo NÃO faz parte do grupo “Processos de gerenciamento de escopo”? ");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaogrupo = new javax.swing.ButtonGroup();
        fQuestaoB = new javax.swing.JRadioButton();
        fQuestaoA = new javax.swing.JRadioButton();
        fQuestaoD = new javax.swing.JRadioButton();
        fQuestaoC = new javax.swing.JRadioButton();
        fConfirmar = new javax.swing.JButton();
        fLabelA = new javax.swing.JLabel();
        fLabelB = new javax.swing.JLabel();
        fLabelC = new javax.swing.JLabel();
        fLabelD = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fTextField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        botaogrupo.add(fQuestaoB);
        fQuestaoB.setText("B)");

        botaogrupo.add(fQuestaoA);
        fQuestaoA.setText("A)");
        fQuestaoA.setActionCommand("fQuestaoA");
        fQuestaoA.setName("fQuestaoA"); // NOI18N

        botaogrupo.add(fQuestaoD);
        fQuestaoD.setText("D)");

        botaogrupo.add(fQuestaoC);
        fQuestaoC.setText("C)");

        fConfirmar.setText("Confirmar");
        fConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fConfirmarMouseClicked(evt);
            }
        });

        fLabelA.setText("a");

        fLabelB.setText("a");

        fLabelC.setText("a");

        fLabelD.setText("a");

        fTextField.setEditable(false);
        fTextField.setColumns(20);
        fTextField.setRows(5);
        jScrollPane1.setViewportView(fTextField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fConfirmar)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fQuestaoD)
                            .addComponent(fQuestaoC)
                            .addComponent(fQuestaoB)
                            .addComponent(fQuestaoA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fLabelB, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fLabelC, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fLabelD, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fQuestaoA)
                    .addComponent(fLabelA))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fQuestaoB)
                    .addComponent(fLabelB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fQuestaoC)
                    .addComponent(fLabelC))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fQuestaoD)
                    .addComponent(fLabelD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(fConfirmar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fConfirmarMouseClicked
       // fPergunta.setText("Mudou o texto");
    }//GEN-LAST:event_fConfirmarMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.teste();
    }//GEN-LAST:event_formWindowActivated

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botaogrupo;
    private javax.swing.JButton fConfirmar;
    private javax.swing.JLabel fLabelA;
    private javax.swing.JLabel fLabelB;
    private javax.swing.JLabel fLabelC;
    private javax.swing.JLabel fLabelD;
    private javax.swing.JRadioButton fQuestaoA;
    private javax.swing.JRadioButton fQuestaoB;
    private javax.swing.JRadioButton fQuestaoC;
    private javax.swing.JRadioButton fQuestaoD;
    private javax.swing.JTextArea fTextField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
